#!/usr/bin/env python


import argparse


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--foo', dest='foo')
    args = parser.parse_known_args()
    print repr(args)


